os: linux
language: python
compiler: g++

jobs:
  include:
    - os: linux
      dist: focal
      python: 3.7
      env: DISTRIBUTION="python"
    - os: linux
      dist: focal
      python: 3.8
      env: DISTRIBUTION="python"
    - os: linux
      dist: focal
      python: 3.9
      env: DISTRIBUTION="python"
    - os: linux
      dist: focal
      python: 3.10
      env: DISTRIBUTION="python"
    - os: linux
      dist: bionic
      env: DISTRIBUTION="python"
    - os: linux
      dist: focal
      env: DISTRIBUTION="conda"

branches:
  only:
    - pypi
    - /^v\d+\.\d+\.\d+.*$/  # version tags

notifications:
  email:
    recipients:
      - francesco.ruscelli@iit.it
      - arturo.laurenzi@iit.it
      - enrico.mingo@pal-robotics.com
    on_success: never
    on_failure: always

# before_install:
  # - rm -rf /opt/pyenv

before_script:
  - export SRC_DIR=$PWD
  - export FOREST_DIR=$PWD/../forest_ws

  - ./travis/init.sh

script:

  - ./travis/run.sh
