package:
  name: casadi_kin_dyn
  version: "0.0.4"

source:
  path: ..
  # git_url: https://github.com/ADVRHumanoids/casadi_kin_dyn.git
  # git_rev: pypi

build:
  number: 1
  python:  {{ python }}

requirements:
  build:
    - python {{ python }}
    - casadi
    - hpp-pinocchio # (necessary for hpp-flc that the branch collision uses)
    - pybind11
    - urdfdom
    - compilers
    - cmake
    - conda-build
    - conda-verify
    - anaconda-client
    - gxx_linux-64  # required for a bug in letsee (which is actually not necessary)
  run:
    - python # this is required to 'activate' the build matrix for multiple versions of python

test:
  source_files:
    - tests/cart_pole.urdf # include urdf for testing
  requires:
    - scipy
    - casadi
    - numpy
    - pybind11
    - urdfdom
    - matplotlib
    - pytest

about:
  home: https://github.com/ADVRHumanoids/casadi_kin_dyn
  summary: "Package for generation of symbolic (SX) expressions of robot kinematics and dynamics. Based on URDF and Pinocchio."